diff --git a/extensions/browser/extension_function_histogram_value.h b/extensions/browser/extension_function_histogram_value.h
index ef1e808e09269..0d8e46d362f80 100644
--- a/extensions/browser/extension_function_histogram_value.h
+++ b/extensions/browser/extension_function_histogram_value.h
@@ -2017,6 +2017,32 @@ enum HistogramValue {
   WEBSTOREPRIVATE_SHOULDSHOWENTERPRISEPROMOTIONBANNER = 1954,
   WEBSTOREPRIVATE_LOGENTERPRISEPROMOSHOWN = 1955,
   WEBSTOREPRIVATE_ONENTERPRISEPROMOCLICK = 1956,
+  // BrowserOS: extension function histogram values
+  BROWSER_OS_GETACCESSIBILITYTREE = 1957,
+  BROWSER_OS_GETINTERACTIVESNAPSHOT = 1958,
+  BROWSER_OS_CLICK = 1959,
+  BROWSER_OS_INPUTTEXT = 1960,
+  BROWSER_OS_CLEAR = 1961,
+  BROWSER_OS_GETPAGELOADSTATUS = 1962,
+  BROWSER_OS_SCROLLUP = 1963,
+  BROWSER_OS_SCROLLDOWN = 1964,
+  BROWSER_OS_SCROLLTONODE = 1965,
+  BROWSER_OS_SENDKEYS = 1966,
+  BROWSER_OS_GETPAGESTRUCTURE = 1967,
+  BROWSER_OS_CAPTURESCREENSHOT = 1968,
+  BROWSER_OS_GETSNAPSHOT = 1969,
+  BROWSER_OS_GETPREF = 1970,
+  BROWSER_OS_SETPREF = 1971,
+  BROWSER_OS_GETALLPREFS = 1972,
+  BROWSER_OS_LOGMETRIC = 1973,
+  BROWSER_OS_GETVERSIONNUMBER = 1974,
+  BROWSER_OS_EXECUTEJAVASCRIPT = 1975,
+  BROWSER_OS_CLICKCOORDINATES = 1976,
+  BROWSER_OS_TYPEATCOORDINATES = 1977,
+  SIDEPANEL_BROWSEROSTOGGLE = 1978,
+  SIDEPANEL_BROWSEROSISOPEN = 1979,
+  BROWSER_OS_GETBROWSEROSVERSIONNUMBER = 1980,
+  BROWSER_OS_CHOOSEPATH = 1981,
   // Last entry: Add new entries above, then run:
   // tools/metrics/histograms/update_extension_histograms.py
   ENUM_BOUNDARY
